### ISSUE TITLE
Problem parsing <a> tags in list

### ISSUE THREAD

**Issue by bogdan-pechounov** [Aghajari/AnnotatedText#2]
For the page https://en.wikipedia.org/wiki/Gwynfryn, there is an issue parsing `<a>` tags.
![image](https://github.com/Aghajari/AnnotatedText/assets/119967588/6c7ddba5-662d-4983-8e92-15ecb43fb319)

![image](https://github.com/Aghajari/AnnotatedText/assets/119967588/a4783fc1-1d08-46f4-9b88-9c79703f8578)

```
val html =
                    "<ul><li><a href=\"/wiki/Hugh_Ellis-Nanney#Plas_Gwynfryn\" title=\"Hugh Ellis-Nanney\">Plas Gwynfryn</a>, <a href=\"/wiki/Criccieth\" title=\"Criccieth\">Criccieth</a>, <a href=\"/wiki/North_Wales\" title=\"North Wales\">North Wales</a>, <a href=\"/wiki/UK\" class=\"mw-redirect\" title=\"UK\">UK</a></li>\n" +
                            "<li><a href=\"/wiki/Gwynfryn,_Gwynedd\" class=\"mw-redirect\" title=\"Gwynfryn, Gwynedd\">Gwynfryn, Gwynedd</a>, Wales</li>\n" +
                            "<li><a href=\"/wiki/Gwynfryn,_Wrexham\" title=\"Gwynfryn, Wrexham\">Gwynfryn, Wrexham</a>, Wales</li>\n" +
                            "<li><a href=\"/wiki/Gwynfryn,_London\" class=\"mw-redirect\" title=\"Gwynfryn, London\">Gwynfryn, London</a>, London</li></ul>"
                Text(text = html.fromHtml().annotatedString)
```

It might be the `,` that's causing issues.
```
<ul>
  <li>
    <a href="/wiki/Hugh_Ellis-Nanney#Plas_Gwynfryn" title="Hugh Ellis-Nanney"
      >Plas Gwynfryn</a
    >, <a href="/wiki/Criccieth" title="Criccieth">Criccieth</a>,
    <a href="/wiki/North_Wales" title="North Wales">North Wales</a>,
    <a href="/wiki/UK" class="mw-redirect" title="UK">UK</a>
  </li>
  <li>
    <a
      href="/wiki/Gwynfryn,_Gwynedd"
      class="mw-redirect"
      title="Gwynfryn, Gwynedd"
      >Gwynfryn, Gwynedd</a
    >, Wales
  </li>
  <li>
    <a href="/wiki/Gwynfryn,_Wrexham" title="Gwynfryn, Wrexham"
      >Gwynfryn, Wrexham</a
    >, Wales
  </li>
  <li>
    <a
      href="/wiki/Gwynfryn,_London"
      class="mw-redirect"
      title="Gwynfryn, London"
      >Gwynfryn, London</a
    >, London
  </li>
</ul>
```

**Comment by bogdan-pechounov** [comment]
On a minor note, there is a problem downloading sources.
![image](https://github.com/Aghajari/AnnotatedText/assets/119967588/d4d67ec6-defe-42c6-a3f2-1edb28b606b8)

```
* What went wrong:
Execution failed for task ':app:DownloadSources'.
> Could not resolve all files for configuration ':app:downloadSources_41200de1-9671-493f-8704-698b88d833e7'.
   > Could not find io.github.aghajari:AnnotatedText:1.0.0@aar.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/io/github/aghajari/AnnotatedText/1.0.0@aar/AnnotatedText-1.0.0@aar.pom
       - https://repo.maven.apache.org/maven2/io/github/aghajari/AnnotatedText/1.0.0@aar/AnnotatedText-1.0.0@aar.pom
     Required by:
         project :app
```

The url `https://repo.maven.apache.org/maven2/io/github/aghajari/AnnotatedText/1.0.0@aar/AnnotatedText-1.0.0@aar.pom`  returns 404 Not Found. However, the url `https://repo.maven.apache.org/maven2/io/github/aghajari/AnnotatedText/1.0.0/AnnotatedText-1.0.0.aar` does exist. It seems that Android Studio is expecting a different name.

**Comment by Aghajari** [comment]
Hello @bogdan-pechounov ,

Thank you for reporting the issue. I appreciate your help in identifying and addressing it. The problem, which was related to sorting spans, has been fixed in the [last commit](https://github.com/Aghajari/AnnotatedText/commit/9ffae212d25c6c3aa9f92e7d389803008a8d311d). I'll release a new version with the fix very soon.

**Comment by bogdan-pechounov** [comment]
Thank you for the quick fix! 

It should also fix an issue where spans are used with images. 

https://en.wikipedia.org/wiki/2022_Keio_Challenger
![image](https://github.com/Aghajari/AnnotatedText/assets/119967588/f8b07b02-3857-40cf-b5a4-354ad3e236ea)
![image](https://github.com/Aghajari/AnnotatedText/assets/119967588/1d2e6098-9442-41b0-8bdd-707cd1c6365e)
![image](https://github.com/Aghajari/AnnotatedText/assets/119967588/0ea87a60-ba59-43af-bf5f-bf47b2cceb91)
